# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa1a26471473efc9c03737a8e2da590f62ff7865cbc3cee3736db7d14829c21d422a238eda656e9f7d2fc0565ad97a96029f61ab92f12b41f0555434f3e591fd

test:
  secret_key_base: c9e6a80db4256ffa66f65db778556da802c68bce35f49e61f458b56acf67d80a720d68ef1b8d2a17634dab47f361bf43bcc2c81a3888b3749b75f2d49e7ec4be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
